name: "Setup Steps"
description: "install & build"
inputs:
  skip-build:
    description: Skip the build step if it's not necessary
    required: false
    default: "false"

permissions:
  contents: write
  id-token: write

runs:
  using: "composite"
  steps:
    - name: Install node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: 22

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      id: pnpm-install
      with:
        version: 9.1.1

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install
      shell: bash
      run: pnpm install

    - name: Build
      shell: bash
      if: ${{inputs.skip-build != 'true'}}
      run: pnpm build
