name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: set version for this release
        default: "minor"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"
          - "prerelease"

permissions:
  contents: write
  id-token: write
  attestations: write

env:
  PACKAGE_NAME: "@ledgerhq/exchange-sdk"
  NPM_REGISTRY: jfrog.ledgerlabs.net/artifactory/api/npm/ptx-npm-prod-public

jobs:
  release:
    name: Release
    runs-on: public-ledgerhq-shared-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16
          cache: pnpm

      - name: Setup jq
        run: sudo apt-get install jq

      - name: Setup temp github user
        run: |
          git config user.email "action@github.com"
          git config user.name "Github Bot"

      - name: Install Dependencies
        run: pnpm --frozen-lockfile --filter exchange-sdk install

      - name: Login to JFrog Ledger
        id: jfrog-login
        uses: LedgerHQ/actions-security/actions/jfrog-login@actions/jfrog-login-1

      - name: Configure npm authentication
        run: |
          NPM_RC="$(mktemp)"
          echo "@ledgerhq:registry=https://${{ env.NPM_REGISTRY }}/" > "$NPM_RC"
          echo "//${{ env.NPM_REGISTRY }}/:_authToken=${{ steps.jfrog-login.outputs.oidc-token }}" >> "$NPM_RC"
          echo "//${{ env.NPM_REGISTRY }}/:always-auth=true" >> "$NPM_RC"
          echo "NPM_CONFIG_USERCONFIG=$NPM_RC" >> "$GITHUB_ENV"

      - name: Set current JFrog registry version in package.json
        working-directory: ./lib
        run: jq --arg v "$(pnpm show $PACKAGE_NAME version)" '.version=$v' package.json > tmp && mv tmp package.json

      - name: Create new version
        working-directory: ./lib
        run: pnpm version ${{ inputs.version }} --no-git-tag-version --workspaces-update false

      - name: 📦 Get new version
        id: get_version
        working-directory: ./lib
        run: |
          NEW_VERSION=$(jq -r ".version" package.json)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version is: $NEW_VERSION"

      - name: ✏️ Update version in TrackingService.ts
        run: |
          # Get the version from the previous step's output
          VERSION_STRING="${{ steps.get_version.outputs.version }}"
          FILE_PATH="lib/src/version.ts"

          echo "Updating version in $FILE_PATH to $VERSION_STRING"
          sed -i "s@version: \"1.0.0\",@version: \"$VERSION_STRING\",@" $FILE_PATH

      - name: Build exchange-sdk
        run: pnpm --filter exchange-sdk build

      - name: Publish package to JFrog registry
        run: pnpm publish --filter exchange-sdk --no-git-checks

      - name: Revert git changes and push version tag
        working-directory: ./lib
        run: |
          VERSION="v$(jq -r ".version" ./package.json)"
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          git checkout $GIT_HASH -- ./package.json
          git tag "$VERSION"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
