name: Release-Test

on:
  push:
    env:
      PACKAGE_NAME: "@ledgerhq/exchange-sdk"
    # inputs:
    #   version:
    #     description: set version for this release
    #     default: "minor"
    #     type: choice
    #     options:
    #       - "major"
    #       - "minor"
    #       - "patch"
    #       - "prerelease"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Echo package name
        run: echo $PACKAGE_NAME
