name: Release-Test

on:
  push

env:
  PACKAGE_NAME: "@ledgerhq/exchange-sdk"


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          
      - name: Setup jq
        run: sudo apt-get install jq

      - name: Setup temp github user
        run: |
          git config user.email "action@github.com"
          git config user.name "Github Bot"

      - name: Install Dependencies
        run: pnpm --frozen-lockfile install

      - name: Build exchange-sdk
        run: pnpm --filter exchange-sdk build

      - name: Get version of package from registry
        working-directory: ./lib
        run: PACKAGE_VERSION=$(npm show $PACKAGE_NAME version)
      
      - name: Set version in package.json
        working-directory: ./lib
        run: jq --arg v "$PACKAGE_VERSION" '.version=$v' package.json > tmp && mv tmp package.json

      working-directory: ./lib
      - name: Create new version
        run: pnpm version minor --no-git-tag-version





